<?php if($block->getData('widgettitle')): ?>
            <h2 class='chinhmagento-title'><?php echo $block->getData('widgettitle'); ?></h2>
<?php endif; ?>
<?php if($block->getData('widgetcontent')): ?>
            <h2 class='chinhmagento-content'><?php echo $block->getData('widgetcontent'); ?></h2>
<?php endif; ?>
<?php if($block->getData('widgetauthor')): ?>
            <h2 class='chinhmagento-content'><?php echo $block->getData('widgetauthor'); ?></h2>
<?php endif; ?>